(*Internal (private) data types*)

TYPE
	AutoStateEnum : 
		(
		AUTO_IDLE,
		AUTO_WAIT_FOR_BOX,
		AUTO_PREPARE_UPPER_HANDOVER,
		AUTO_HANDOVER_UPPER_BOX,
		AUTO_PREPARE_LOWER_HANDOVER,
		AUTO_HANDOVER_LOWER_BOX,
		AUTO_HANDOVER_TO_UNLOAD,
		AUTO_UNLOAD_BOX
		);
END_TYPE
